### ISSUE TITLE
which one is the real bundle? this or the pomm-project bundle?

### ISSUE THREAD

**Issue by cordoval** [chanmix51/PommBundle#27]

**Comment by chanmix51** [comment]
This bundle is suited for Pomm 1.x

**Comment by cordoval** [comment]
thanks

**Comment by chanmix51** [comment]
Indicate Pomm version in the README

**Comment by cordoval** [comment]
done in #31 please merge @chanmix51  thanks

https://pbs.twimg.com/tweet_video/CE-zTRWUMAAcCpQ.mp4 :+1:

**Comment by sstok** [comment]
@cordoval https://imgflip.com/gifgenerator

**Comment by cordoval** [comment]
cc @sstok thanks I updated thread :+1:
